/*
 * OTA_Cfg.h
 *
 *  Created on: 26.09.2017
 *      Author: Jean-Martin George
 */

#ifndef FOTA_CFG_H_
#define FOTA_CFG_H_


/******* SERVER CONFIG *********/
#define OTA_SERVER_HOST_NAME      "ds216jmg.ddns.net"
#define OTA_SERVER_METADATA_PATH  "/esp32/ota_cfg.txt"

#define FOTA_SERVER_HOST_NAME		"192.168.1.109"
#define FOTA_SERVER_PORT      		"80"
#define FOTA_BINARY_FILE_NAME		"/esp32/ESP32.bin"



/******* CERTIFICATE *********/

/* chain.pem (server certificate)*/
#define OTA_PEER_PEM \
		"-----BEGIN CERTIFICATE-----\n" \
		"MIIENDCCAxygAwIBAgIHFQWUCAPRAjANBgkqhkiG9w0BAQsFADCBlzELMAkGA1UE\n" \
		"BhMCREUxGzAZBgNVBAgMEkJhZGVuLVd1ZXJ0dGVtYmVyZzERMA8GA1UEBwwITGVv\n" \
		"bmJlcmcxDDAKBgNVBAoMA0pNRzEQMA4GA1UECwwHSGltc2VsZjEMMAoGA1UEAwwD\n" \
		"Sk1HMSowKAYJKoZIhvcNAQkBFhtqZWFubWFydGluLmdlb3JnZUBnbWFpbC5jb20w\n" \
		"HhcNMTgwMjI3MTkwMTQ4WhcNMjgwMjI1MTkwMTQ4WjCBoTELMAkGA1UEBhMCREUx\n" \
		"GzAZBgNVBAgMEkJhZGVuLVd1ZXJ0dGVtYmVyZzERMA8GA1UEBwwITGVvbmJlcmcx\n" \
		"DDAKBgNVBAoMA0pNRzEQMA4GA1UECwwHSGltc2VsZjEWMBQGA1UEAwwNMTkyLjE2\n" \
		"OC4xLjEwOTEqMCgGCSqGSIb3DQEJARYbamVhbm1hcnRpbi5nZW9yZ2VAZ21haWwu\n" \
		"Y29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvnaarrGnZL6cwFHm\n" \
		"JMnd6E98iY7oyxOyfyAQ+uq0bv8jZJSsxQmOfQqqny4NstTJtJi0M4tXCySDX0lu\n" \
		"McJHRvZ+e9hT9xkf+iPkiGa7/c+ay2liBhRWxFV17l1wqa4aWYtZbO2ni8VKH5NG\n" \
		"ecZ/2KOo90PNR6/k2SaKT9vUuQd/Ub1cih8nE1KSPB11DAM5I156uONfVhAf6SYI\n" \
		"bu1dUKM9y1h7mIv1PRqWKFeCnyljzQwnnrEKaTSMXPts0NPrEQSh9uuJypsPRzIj\n" \
		"LEgj/7350dbhCLRzFgeK3Kb5JyVP0e5XOwLKA4CaTF3Hiy+YxQOt5/UE+kWYsCr/\n" \
		"UhEfpQIDAQABo3kwdzAmBgNVHREEHzAdgRtqZWFubWFydGluLmdlb3JnZUBnbWFp\n" \
		"bC5jb20wOgYJYIZIAYb4QgENBC0WK21vZF9zc2wgZ2VuZXJhdGVkIGN1c3RvbSBz\n" \
		"ZXJ2ZXIgY2VydGlmaWNhdGUwEQYJYIZIAYb4QgEBBAQDAgZAMA0GCSqGSIb3DQEB\n" \
		"CwUAA4IBAQDHLOxW0oQfIW8q+8+PeypwMDPgjeTa1KaKsEEEUk6X8M0A9KrDT0l3\n" \
		"i8b2RK1M8t4kNZUVLo5kjyaiBDuU+uaW/X/SXU8Api+yVFdn9w8GO0Y2yk2qoD88\n" \
		"Wj5uhO2r1/Q6QB4FdIDX/5+uQfnXTow/NSCio3OLWQRCRsm5JIjxn/CzdVJgUWPF\n" \
		"Dolh3K05/xC/vkigE/2l3pwTSr8Uc8YhfYXLthanNn8WVQQ7J8q+yMB5mJ/brCTB\n" \
		"QjP/iJoBzcAQ1e+d4F9nkW7O3guSfBGEhlxQDGrY2kQ1690O/EIrdb9HYlfkcOo1\n" \
		"BbkZ8XSjPLx4dobSiTW5jxkL7cjyI5YT\n" \
		"-----END CERTIFICATE-----\n"


/* cert.pem (root certificate) */
#define OTA_SERVER_ROOT_CA_PEM \
		"-----BEGIN CERTIFICATE-----\n" \
		"MIIEOzCCAyOgAwIBAgIJANWGWhcAbodNMA0GCSqGSIb3DQEBCwUAMIGXMQswCQYD\n" \
		"VQQGEwJERTEbMBkGA1UECAwSQmFkZW4tV3VlcnR0ZW1iZXJnMREwDwYDVQQHDAhM\n" \
		"ZW9uYmVyZzEMMAoGA1UECgwDSk1HMRAwDgYDVQQLDAdIaW1zZWxmMQwwCgYDVQQD\n" \
		"DANKTUcxKjAoBgkqhkiG9w0BCQEWG2plYW5tYXJ0aW4uZ2VvcmdlQGdtYWlsLmNv\n" \
		"bTAeFw0xODAyMjcxOTAxNDZaFw0yODAyMjUxOTAxNDZaMIGXMQswCQYDVQQGEwJE\n" \
		"RTEbMBkGA1UECAwSQmFkZW4tV3VlcnR0ZW1iZXJnMREwDwYDVQQHDAhMZW9uYmVy\n" \
		"ZzEMMAoGA1UECgwDSk1HMRAwDgYDVQQLDAdIaW1zZWxmMQwwCgYDVQQDDANKTUcx\n" \
		"KjAoBgkqhkiG9w0BCQEWG2plYW5tYXJ0aW4uZ2VvcmdlQGdtYWlsLmNvbTCCASIw\n" \
		"DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANDIgCxm4bFOW5p7r0ub1NWajgwx\n" \
		"TKhD4gPQKhza5dtRQn779y8vIIh9uIpI7Aj2dCvFbGtUA2SIjFI1caCIrKmpINTE\n" \
		"rAiUU/exwaGmp7S/wa+Ssfg2CU0ryN+hJhyc8n4gvBEvFiUlyUPub0g8qwyidZ+J\n" \
		"xrbUnRLTwG/ID8VBt3kmaNs+7mwNrn8j5TNPS1hmkDWFGWj0/zsq4KH4txGvdK0l\n" \
		"8c21+LuVNkUL+EtaQhVn3Wf912YimEGxoVpCE9YTbghNL/aZ7nFJkM80CltloM61\n" \
		"ne6zd4ycjiEf24EmI9jfGj2Gkss/M0gmrdTXLwS1Qk8jwGRQrZC7XcQJspcCAwEA\n" \
		"AaOBhzCBhDAmBgNVHREEHzAdgRtqZWFubWFydGluLmdlb3JnZUBnbWFpbC5jb20w\n" \
		"DwYDVR0TBAgwBgEB/wIBADA2BglghkgBhvhCAQ0EKRYnbW9kX3NzbCBnZW5lcmF0\n" \
		"ZWQgY3VzdG9tIENBIGNlcnRpZmljYXRlMBEGCWCGSAGG+EIBAQQEAwICBDANBgkq\n" \
		"hkiG9w0BAQsFAAOCAQEAOX07C9KFm9W9wTPOLrQLqKyF1VT1lrg2oizKMWatVOL+\n" \
		"jAs7frqT1CQI6unDU8XMLaCLefUm0VjeBZYCTbFh/j0yHVBm/3ejkj3Op8pe4Igf\n" \
		"/v1/t9FMUB+50JJCJZipYdPalBKR+SkZ9UCkPo4m8M0It5A9nlNHprEcMg+hsWcm\n" \
		"+ZUsAu5Iys0rU9bcibPggvAVjhdXs8zkXb9AtkYBLquebAMuclTupq6GCSW4yVwJ\n" \
		"S3y3brmAwHKmYoc/XeWwX7BVwxhMsbxj0TQ0S19gDDpDepbEeU8Vk1LLpMvZpPl3\n" \
		"zANtbFXJot9XYdGATLiHeF9XRTNWAXtJWLAvfDYyGw==\n" \
		"-----END CERTIFICATE-----\n"


#endif /* FOTA_CFG_H_ */
